// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AIProposal struct {
	ID           string               `json:"id"`
	ParentType   AIProposalParentType `json:"parentType"`
	ParentID     string               `json:"parentId"`
	MagicText    string               `json:"magicText"`
	Summary      string               `json:"summary"`
	ProposalJSON string               `json:"proposalJson"`
	Status       AIProposalStatus     `json:"status"`
	CreatedAt    time.Time            `json:"createdAt"`
	AppliedAt    *time.Time           `json:"appliedAt,omitempty"`
}

type AIProposalFilter struct {
	ParentType *AIProposalParentType `json:"parentType,omitempty"`
	ParentID   *string               `json:"parentId,omitempty"`
}

type AIStatusReport struct {
	Summary string `json:"summary"`
	Ready   bool   `json:"ready"`
}

type CreateEpicInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Color       *string `json:"color,omitempty"`
	Position    *int    `json:"position,omitempty"`
}

type CreateLabelInput struct {
	Name  string  `json:"name"`
	Color *string `json:"color,omitempty"`
}

type CreateProjectInput struct {
	EpicID      *string        `json:"epicId,omitempty"`
	Name        string         `json:"name"`
	Description *string        `json:"description,omitempty"`
	Status      *ProjectStatus `json:"status,omitempty"`
	StartDate   *time.Time     `json:"startDate,omitempty"`
	TargetDate  *time.Time     `json:"targetDate,omitempty"`
	Position    *int           `json:"position,omitempty"`
}

type CreateProjectNoteInput struct {
	ProjectID string `json:"projectId"`
	Body      string `json:"body"`
}

type CreateStageInput struct {
	ProjectID   string       `json:"projectId"`
	Name        string       `json:"name"`
	Description *string      `json:"description,omitempty"`
	Status      *StageStatus `json:"status,omitempty"`
	StartDate   *time.Time   `json:"startDate,omitempty"`
	TargetDate  *time.Time   `json:"targetDate,omitempty"`
	Position    *int         `json:"position,omitempty"`
}

type CreateTodoInput struct {
	ProjectID       *string       `json:"projectId,omitempty"`
	StageID         *string       `json:"stageId,omitempty"`
	Title           string        `json:"title"`
	Description     *string       `json:"description,omitempty"`
	Priority        *TodoPriority `json:"priority,omitempty"`
	Status          *TodoStatus   `json:"status,omitempty"`
	StartDate       *time.Time    `json:"startDate,omitempty"`
	DueDate         *time.Time    `json:"dueDate,omitempty"`
	EstimatedEffort *string       `json:"estimatedEffort,omitempty"`
	Position        *int          `json:"position,omitempty"`
	NextAction      *bool         `json:"nextAction,omitempty"`
	Milestone       *bool         `json:"milestone,omitempty"`
	Recurrence      *Recurrence   `json:"recurrence,omitempty"`
}

type Dashboard struct {
	OpenTodos         int `json:"openTodos"`
	OverdueTodos      int `json:"overdueTodos"`
	NextActions       int `json:"nextActions"`
	ActiveProjects    int `json:"activeProjects"`
	UpcomingDeadlines int `json:"upcomingDeadlines"`
}

type Epic struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	Color       *string   `json:"color,omitempty"`
	Position    int       `json:"position"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type GenerateAIProposalInput struct {
	ParentType AIProposalParentType `json:"parentType"`
	ParentID   string               `json:"parentId"`
	MagicText  string               `json:"magicText"`
}

type Label struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Color     *string   `json:"color,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Mutation struct {
}

type Progress struct {
	Total   int `json:"total"`
	Done    int `json:"done"`
	Percent int `json:"percent"`
}

type Project struct {
	ID          string        `json:"id"`
	EpicID      *string       `json:"epicId,omitempty"`
	Name        string        `json:"name"`
	Description *string       `json:"description,omitempty"`
	Status      ProjectStatus `json:"status"`
	StartDate   *time.Time    `json:"startDate,omitempty"`
	TargetDate  *time.Time    `json:"targetDate,omitempty"`
	Position    int           `json:"position"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

type ProjectNote struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"projectId"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Query struct {
}

type Stage struct {
	ID          string      `json:"id"`
	ProjectID   string      `json:"projectId"`
	Name        string      `json:"name"`
	Description *string     `json:"description,omitempty"`
	Status      StageStatus `json:"status"`
	StartDate   *time.Time  `json:"startDate,omitempty"`
	TargetDate  *time.Time  `json:"targetDate,omitempty"`
	Position    int         `json:"position"`
	CreatedAt   time.Time   `json:"createdAt"`
	UpdatedAt   time.Time   `json:"updatedAt"`
}

type Todo struct {
	ID              string       `json:"id"`
	ProjectID       *string      `json:"projectId,omitempty"`
	StageID         *string      `json:"stageId,omitempty"`
	Title           string       `json:"title"`
	Description     *string      `json:"description,omitempty"`
	Priority        TodoPriority `json:"priority"`
	Status          TodoStatus   `json:"status"`
	Labels          []*Label     `json:"labels"`
	StartDate       *time.Time   `json:"startDate,omitempty"`
	DueDate         *time.Time   `json:"dueDate,omitempty"`
	EstimatedEffort *string      `json:"estimatedEffort,omitempty"`
	Position        int          `json:"position"`
	NextAction      bool         `json:"nextAction"`
	Milestone       bool         `json:"milestone"`
	Recurrence      Recurrence   `json:"recurrence"`
	CompletedAt     *time.Time   `json:"completedAt,omitempty"`
	CreatedAt       time.Time    `json:"createdAt"`
	UpdatedAt       time.Time    `json:"updatedAt"`
}

type TodoDependency struct {
	TodoID          string    `json:"todoId"`
	DependsOnTodoID string    `json:"dependsOnTodoId"`
	CreatedAt       time.Time `json:"createdAt"`
}

type TodoFilter struct {
	ProjectID *string       `json:"projectId,omitempty"`
	StageID   *string       `json:"stageId,omitempty"`
	LabelID   *string       `json:"labelId,omitempty"`
	Priority  *TodoPriority `json:"priority,omitempty"`
	Status    *TodoStatus   `json:"status,omitempty"`
}

type UpdateEpicInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Color       *string `json:"color,omitempty"`
	Position    *int    `json:"position,omitempty"`
}

type UpdateLabelInput struct {
	Name  *string `json:"name,omitempty"`
	Color *string `json:"color,omitempty"`
}

type UpdateProjectInput struct {
	EpicID      *string        `json:"epicId,omitempty"`
	Name        *string        `json:"name,omitempty"`
	Description *string        `json:"description,omitempty"`
	Status      *ProjectStatus `json:"status,omitempty"`
	StartDate   *time.Time     `json:"startDate,omitempty"`
	TargetDate  *time.Time     `json:"targetDate,omitempty"`
	Position    *int           `json:"position,omitempty"`
}

type UpdateProjectNoteInput struct {
	Body *string `json:"body,omitempty"`
}

type UpdateStageInput struct {
	Name        *string      `json:"name,omitempty"`
	Description *string      `json:"description,omitempty"`
	Status      *StageStatus `json:"status,omitempty"`
	StartDate   *time.Time   `json:"startDate,omitempty"`
	TargetDate  *time.Time   `json:"targetDate,omitempty"`
	Position    *int         `json:"position,omitempty"`
}

type UpdateTodoInput struct {
	ProjectID       *string       `json:"projectId,omitempty"`
	StageID         *string       `json:"stageId,omitempty"`
	Title           *string       `json:"title,omitempty"`
	Description     *string       `json:"description,omitempty"`
	Priority        *TodoPriority `json:"priority,omitempty"`
	Status          *TodoStatus   `json:"status,omitempty"`
	StartDate       *time.Time    `json:"startDate,omitempty"`
	DueDate         *time.Time    `json:"dueDate,omitempty"`
	EstimatedEffort *string       `json:"estimatedEffort,omitempty"`
	Position        *int          `json:"position,omitempty"`
	NextAction      *bool         `json:"nextAction,omitempty"`
	Milestone       *bool         `json:"milestone,omitempty"`
	Recurrence      *Recurrence   `json:"recurrence,omitempty"`
}

type AIProposalParentType string

const (
	AIProposalParentTypeEpic    AIProposalParentType = "EPIC"
	AIProposalParentTypeProject AIProposalParentType = "PROJECT"
)

var AllAIProposalParentType = []AIProposalParentType{
	AIProposalParentTypeEpic,
	AIProposalParentTypeProject,
}

func (e AIProposalParentType) IsValid() bool {
	switch e {
	case AIProposalParentTypeEpic, AIProposalParentTypeProject:
		return true
	}
	return false
}

func (e AIProposalParentType) String() string {
	return string(e)
}

func (e *AIProposalParentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AIProposalParentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AIProposalParentType", str)
	}
	return nil
}

func (e AIProposalParentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AIProposalParentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AIProposalParentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AIProposalStatus string

const (
	AIProposalStatusDraft   AIProposalStatus = "DRAFT"
	AIProposalStatusApplied AIProposalStatus = "APPLIED"
)

var AllAIProposalStatus = []AIProposalStatus{
	AIProposalStatusDraft,
	AIProposalStatusApplied,
}

func (e AIProposalStatus) IsValid() bool {
	switch e {
	case AIProposalStatusDraft, AIProposalStatusApplied:
		return true
	}
	return false
}

func (e AIProposalStatus) String() string {
	return string(e)
}

func (e *AIProposalStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AIProposalStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AIProposalStatus", str)
	}
	return nil
}

func (e AIProposalStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AIProposalStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AIProposalStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectStatus string

const (
	ProjectStatusActive   ProjectStatus = "ACTIVE"
	ProjectStatusPaused   ProjectStatus = "PAUSED"
	ProjectStatusDone     ProjectStatus = "DONE"
	ProjectStatusArchived ProjectStatus = "ARCHIVED"
)

var AllProjectStatus = []ProjectStatus{
	ProjectStatusActive,
	ProjectStatusPaused,
	ProjectStatusDone,
	ProjectStatusArchived,
}

func (e ProjectStatus) IsValid() bool {
	switch e {
	case ProjectStatusActive, ProjectStatusPaused, ProjectStatusDone, ProjectStatusArchived:
		return true
	}
	return false
}

func (e ProjectStatus) String() string {
	return string(e)
}

func (e *ProjectStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectStatus", str)
	}
	return nil
}

func (e ProjectStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Recurrence string

const (
	RecurrenceNone    Recurrence = "NONE"
	RecurrenceDaily   Recurrence = "DAILY"
	RecurrenceWeekly  Recurrence = "WEEKLY"
	RecurrenceMonthly Recurrence = "MONTHLY"
	RecurrenceYearly  Recurrence = "YEARLY"
)

var AllRecurrence = []Recurrence{
	RecurrenceNone,
	RecurrenceDaily,
	RecurrenceWeekly,
	RecurrenceMonthly,
	RecurrenceYearly,
}

func (e Recurrence) IsValid() bool {
	switch e {
	case RecurrenceNone, RecurrenceDaily, RecurrenceWeekly, RecurrenceMonthly, RecurrenceYearly:
		return true
	}
	return false
}

func (e Recurrence) String() string {
	return string(e)
}

func (e *Recurrence) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Recurrence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Recurrence", str)
	}
	return nil
}

func (e Recurrence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Recurrence) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Recurrence) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StageStatus string

const (
	StageStatusPlanned    StageStatus = "PLANNED"
	StageStatusInProgress StageStatus = "IN_PROGRESS"
	StageStatusDone       StageStatus = "DONE"
)

var AllStageStatus = []StageStatus{
	StageStatusPlanned,
	StageStatusInProgress,
	StageStatusDone,
}

func (e StageStatus) IsValid() bool {
	switch e {
	case StageStatusPlanned, StageStatusInProgress, StageStatusDone:
		return true
	}
	return false
}

func (e StageStatus) String() string {
	return string(e)
}

func (e *StageStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StageStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StageStatus", str)
	}
	return nil
}

func (e StageStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StageStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StageStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TodoPriority string

const (
	TodoPriorityLow      TodoPriority = "LOW"
	TodoPriorityNormal   TodoPriority = "NORMAL"
	TodoPriorityHigh     TodoPriority = "HIGH"
	TodoPriorityCritical TodoPriority = "CRITICAL"
)

var AllTodoPriority = []TodoPriority{
	TodoPriorityLow,
	TodoPriorityNormal,
	TodoPriorityHigh,
	TodoPriorityCritical,
}

func (e TodoPriority) IsValid() bool {
	switch e {
	case TodoPriorityLow, TodoPriorityNormal, TodoPriorityHigh, TodoPriorityCritical:
		return true
	}
	return false
}

func (e TodoPriority) String() string {
	return string(e)
}

func (e *TodoPriority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TodoPriority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TodoPriority", str)
	}
	return nil
}

func (e TodoPriority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TodoPriority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TodoPriority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TodoStatus string

const (
	TodoStatusOpen       TodoStatus = "OPEN"
	TodoStatusInProgress TodoStatus = "IN_PROGRESS"
	TodoStatusDone       TodoStatus = "DONE"
	TodoStatusBlocked    TodoStatus = "BLOCKED"
)

var AllTodoStatus = []TodoStatus{
	TodoStatusOpen,
	TodoStatusInProgress,
	TodoStatusDone,
	TodoStatusBlocked,
}

func (e TodoStatus) IsValid() bool {
	switch e {
	case TodoStatusOpen, TodoStatusInProgress, TodoStatusDone, TodoStatusBlocked:
		return true
	}
	return false
}

func (e TodoStatus) String() string {
	return string(e)
}

func (e *TodoStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TodoStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TodoStatus", str)
	}
	return nil
}

func (e TodoStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TodoStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TodoStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
