package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"log/slog"
	"time"

	"github.com/donamo/todo-backend/internal/ai"
	dbsqlc "github.com/donamo/todo-backend/internal/db"
	"github.com/donamo/todo-backend/internal/graph/model"
	"github.com/google/uuid"
)

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	q, err := r.requireAdminQueries(ctx)
	if err != nil {
		return nil, err
	}
	userID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	user, err := q.UpdateUser(ctx, dbsqlc.UpdateUserParams{
		ID:       userID,
		Approved: nullBool(input.Approved),
	})
	if err != nil {
		return nil, err
	}
	return toUser(user), nil
}

// CreateEpic is the resolver for the createEpic field.
func (r *mutationResolver) CreateEpic(ctx context.Context, input model.CreateEpicInput) (*model.Epic, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	epic, err := q.CreateEpic(ctx, dbsqlc.CreateEpicParams{
		UserID:      userID,
		Name:        input.Name,
		Description: nullString(input.Description),
		Color:       nullString(input.Color),
		Position:    optionalInt(input.Position),
	})
	if err != nil {
		return nil, err
	}
	return toEpic(epic), nil
}

// UpdateEpic is the resolver for the updateEpic field.
func (r *mutationResolver) UpdateEpic(ctx context.Context, id string, input model.UpdateEpicInput) (*model.Epic, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	epicID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	epic, err := q.UpdateEpic(ctx, dbsqlc.UpdateEpicParams{
		ID:          epicID,
		UserID:      userID,
		Name:        nullString(input.Name),
		Description: nullString(input.Description),
		Color:       nullString(input.Color),
		Position:    nullInt32(input.Position),
	})
	if err != nil {
		return nil, err
	}
	return toEpic(epic), nil
}

// DeleteEpic is the resolver for the deleteEpic field.
func (r *mutationResolver) DeleteEpic(ctx context.Context, id string, keepChildren *bool) (bool, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return false, err
	}
	epicID, err := parseUUID(id)
	if err != nil {
		return false, err
	}
	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return false, err
	}
	defer tx.Rollback()

	tq := q.WithTx(tx)
	epicRef := uuid.NullUUID{UUID: epicID, Valid: true}
	if boolValue(keepChildren, true) {
		if err := tq.DetachProjectsFromEpic(ctx, dbsqlc.DetachProjectsFromEpicParams{EpicID: epicRef, UserID: userID}); err != nil {
			return false, err
		}
	} else {
		if err := tq.DeleteProjectsByEpic(ctx, dbsqlc.DeleteProjectsByEpicParams{EpicID: epicRef, UserID: userID}); err != nil {
			return false, err
		}
	}
	if err := tq.DeleteEpic(ctx, dbsqlc.DeleteEpicParams{ID: epicID, UserID: userID}); err != nil {
		return false, err
	}
	if err := tx.Commit(); err != nil {
		return false, err
	}
	return true, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	epicID, err := nullUUID(input.EpicID)
	if err != nil {
		return nil, err
	}
	project, err := q.CreateProject(ctx, dbsqlc.CreateProjectParams{
		UserID:      userID,
		EpicID:      epicID,
		Name:        input.Name,
		Description: nullString(input.Description),
		Status:      optionalProjectStatus(input.Status),
		StartDate:   nullTime(input.StartDate),
		TargetDate:  nullTime(input.TargetDate),
		Position:    optionalInt(input.Position),
	})
	if err != nil {
		return nil, err
	}
	return toProject(project), nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, input model.UpdateProjectInput) (*model.Project, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	projectID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	epicID, err := nullUUID(input.EpicID)
	if err != nil {
		return nil, err
	}
	project, err := q.UpdateProject(ctx, dbsqlc.UpdateProjectParams{
		ID:          projectID,
		UserID:      userID,
		EpicID:      epicID,
		Name:        nullString(input.Name),
		Description: nullString(input.Description),
		Status:      nullProjectStatus(input.Status),
		StartDate:   nullTime(input.StartDate),
		TargetDate:  nullTime(input.TargetDate),
		Position:    nullInt32(input.Position),
	})
	if err != nil {
		return nil, err
	}
	return toProject(project), nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string, keepChildren *bool) (bool, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return false, err
	}
	projectID, err := parseUUID(id)
	if err != nil {
		return false, err
	}
	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return false, err
	}
	defer tx.Rollback()

	tq := q.WithTx(tx)
	if boolValue(keepChildren, false) {
		projectRef := uuid.NullUUID{UUID: projectID, Valid: true}
		if err := tq.DetachTodosFromProject(ctx, dbsqlc.DetachTodosFromProjectParams{ProjectID: projectRef, UserID: userID}); err != nil {
			return false, err
		}
		if err := tq.DetachStagesFromProject(ctx, dbsqlc.DetachStagesFromProjectParams{ProjectID: projectRef, UserID: userID}); err != nil {
			return false, err
		}
	}
	if err := tq.DeleteProject(ctx, dbsqlc.DeleteProjectParams{ID: projectID, UserID: userID}); err != nil {
		return false, err
	}
	if err := tx.Commit(); err != nil {
		return false, err
	}
	return true, nil
}

// CreateStage is the resolver for the createStage field.
func (r *mutationResolver) CreateStage(ctx context.Context, input model.CreateStageInput) (*model.Stage, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	projectID, err := parseUUID(input.ProjectID)
	if err != nil {
		return nil, err
	}
	stage, err := q.CreateStage(ctx, dbsqlc.CreateStageParams{
		UserID:      userID,
		ProjectID:   uuid.NullUUID{UUID: projectID, Valid: true},
		Name:        input.Name,
		Description: nullString(input.Description),
		Status:      optionalStageStatus(input.Status),
		StartDate:   nullTime(input.StartDate),
		TargetDate:  nullTime(input.TargetDate),
		Position:    optionalInt(input.Position),
	})
	if err != nil {
		return nil, err
	}
	return toStage(stage), nil
}

// UpdateStage is the resolver for the updateStage field.
func (r *mutationResolver) UpdateStage(ctx context.Context, id string, input model.UpdateStageInput) (*model.Stage, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	stageID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	stage, err := q.UpdateStage(ctx, dbsqlc.UpdateStageParams{
		ID:          stageID,
		UserID:      userID,
		Name:        nullString(input.Name),
		Description: nullString(input.Description),
		Status:      nullStageStatus(input.Status),
		StartDate:   nullTime(input.StartDate),
		TargetDate:  nullTime(input.TargetDate),
		Position:    nullInt32(input.Position),
	})
	if err != nil {
		return nil, err
	}
	return toStage(stage), nil
}

// DeleteStage is the resolver for the deleteStage field.
func (r *mutationResolver) DeleteStage(ctx context.Context, id string, keepChildren *bool) (bool, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return false, err
	}
	stageID, err := parseUUID(id)
	if err != nil {
		return false, err
	}
	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return false, err
	}
	defer tx.Rollback()

	tq := q.WithTx(tx)
	stageRef := uuid.NullUUID{UUID: stageID, Valid: true}
	if boolValue(keepChildren, true) {
		if err := tq.DetachTodosFromStage(ctx, dbsqlc.DetachTodosFromStageParams{StageID: stageRef, UserID: userID}); err != nil {
			return false, err
		}
	} else {
		if err := tq.DeleteTodosByStage(ctx, dbsqlc.DeleteTodosByStageParams{StageID: stageRef, UserID: userID}); err != nil {
			return false, err
		}
	}
	if err := tq.DeleteStage(ctx, dbsqlc.DeleteStageParams{ID: stageID, UserID: userID}); err != nil {
		return false, err
	}
	if err := tx.Commit(); err != nil {
		return false, err
	}
	return true, nil
}

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.CreateTodoInput) (*model.Todo, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	projectID, err := nullUUID(input.ProjectID)
	if err != nil {
		return nil, err
	}
	stageID, err := nullUUID(input.StageID)
	if err != nil {
		return nil, err
	}
	todo, err := q.CreateTodo(ctx, dbsqlc.CreateTodoParams{
		UserID:          userID,
		ProjectID:       projectID,
		StageID:         stageID,
		Title:           input.Title,
		Description:     nullString(input.Description),
		Priority:        optionalTodoPriority(input.Priority),
		Status:          optionalTodoStatus(input.Status),
		StartDate:       nullTime(input.StartDate),
		DueDate:         nullTime(input.DueDate),
		EstimatedEffort: nullString(input.EstimatedEffort),
		Position:        optionalInt(input.Position),
		NextAction:      false,
		Milestone:       optionalBool(input.Milestone),
		Recurrence:      optionalRecurrence(input.Recurrence),
	})
	if err != nil {
		return nil, err
	}
	if input.NextAction != nil && *input.NextAction {
		return r.setTodoNextAction(ctx, q, userID, todo.ID, true)
	}
	return r.todoWithLabels(ctx, q, userID, todo)
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, id string, input model.UpdateTodoInput) (*model.Todo, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	todoID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	projectID, err := nullUUID(input.ProjectID)
	if err != nil {
		return nil, err
	}
	stageID, err := nullUUID(input.StageID)
	if err != nil {
		return nil, err
	}
	if input.NextAction != nil && *input.NextAction {
		existing, err := q.GetTodo(ctx, dbsqlc.GetTodoParams{ID: todoID, UserID: userID})
		if err != nil {
			return nil, err
		}
		projectForClear := projectID
		if !projectForClear.Valid {
			projectForClear = existing.ProjectID
		}
		if projectForClear.Valid {
			if err := q.ClearProjectNextActions(ctx, dbsqlc.ClearProjectNextActionsParams{UserID: userID, ProjectID: projectForClear, ID: todoID}); err != nil {
				return nil, err
			}
		}
	}
	todo, err := q.UpdateTodo(ctx, dbsqlc.UpdateTodoParams{
		ID:              todoID,
		UserID:          userID,
		ProjectID:       projectID,
		StageID:         stageID,
		Title:           nullString(input.Title),
		Description:     nullString(input.Description),
		Priority:        nullTodoPriority(input.Priority),
		Status:          nullTodoStatus(input.Status),
		StartDate:       nullTime(input.StartDate),
		DueDate:         nullTime(input.DueDate),
		EstimatedEffort: nullString(input.EstimatedEffort),
		Position:        nullInt32(input.Position),
		NextAction:      nullBool(input.NextAction),
		Milestone:       nullBool(input.Milestone),
		Recurrence:      nullRecurrence(input.Recurrence),
	})
	if err != nil {
		return nil, err
	}
	return r.todoWithLabels(ctx, q, userID, todo)
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (bool, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return false, err
	}
	todoID, err := parseUUID(id)
	if err != nil {
		return false, err
	}
	return true, q.DeleteTodo(ctx, dbsqlc.DeleteTodoParams{ID: todoID, UserID: userID})
}

// MarkTodoDone is the resolver for the markTodoDone field.
func (r *mutationResolver) MarkTodoDone(ctx context.Context, id string) (*model.Todo, error) {
	status := model.TodoStatusDone
	return r.UpdateTodo(ctx, id, model.UpdateTodoInput{Status: &status})
}

// SetTodoNextAction is the resolver for the setTodoNextAction field.
func (r *mutationResolver) SetTodoNextAction(ctx context.Context, id string, nextAction bool) (*model.Todo, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	todoID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	return r.setTodoNextAction(ctx, q, userID, todoID, nextAction)
}

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, input model.CreateLabelInput) (*model.Label, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	label, err := q.CreateLabel(ctx, dbsqlc.CreateLabelParams{UserID: userID, Name: input.Name, Color: nullString(input.Color)})
	if err != nil {
		return nil, err
	}
	return toLabel(label), nil
}

// UpdateLabel is the resolver for the updateLabel field.
func (r *mutationResolver) UpdateLabel(ctx context.Context, id string, input model.UpdateLabelInput) (*model.Label, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	labelID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	label, err := q.UpdateLabel(ctx, dbsqlc.UpdateLabelParams{
		ID:     labelID,
		UserID: userID,
		Name:   nullString(input.Name),
		Color:  nullString(input.Color),
	})
	if err != nil {
		return nil, err
	}
	return toLabel(label), nil
}

// DeleteLabel is the resolver for the deleteLabel field.
func (r *mutationResolver) DeleteLabel(ctx context.Context, id string) (bool, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return false, err
	}
	labelID, err := parseUUID(id)
	if err != nil {
		return false, err
	}
	return true, q.DeleteLabel(ctx, dbsqlc.DeleteLabelParams{ID: labelID, UserID: userID})
}

// AddTodoLabel is the resolver for the addTodoLabel field.
func (r *mutationResolver) AddTodoLabel(ctx context.Context, todoID string, labelID string) (*model.Todo, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	tID, err := parseUUID(todoID)
	if err != nil {
		return nil, err
	}
	lID, err := parseUUID(labelID)
	if err != nil {
		return nil, err
	}
	if err := q.AddTodoLabel(ctx, dbsqlc.AddTodoLabelParams{TodoID: tID, LabelID: lID, UserID: userID}); err != nil {
		return nil, err
	}
	return r.getTodoModel(ctx, q, userID, tID)
}

// RemoveTodoLabel is the resolver for the removeTodoLabel field.
func (r *mutationResolver) RemoveTodoLabel(ctx context.Context, todoID string, labelID string) (*model.Todo, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	tID, err := parseUUID(todoID)
	if err != nil {
		return nil, err
	}
	lID, err := parseUUID(labelID)
	if err != nil {
		return nil, err
	}
	if err := q.RemoveTodoLabel(ctx, dbsqlc.RemoveTodoLabelParams{TodoID: tID, LabelID: lID, UserID: userID}); err != nil {
		return nil, err
	}
	return r.getTodoModel(ctx, q, userID, tID)
}

// CreateProjectNote is the resolver for the createProjectNote field.
func (r *mutationResolver) CreateProjectNote(ctx context.Context, input model.CreateProjectNoteInput) (*model.ProjectNote, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	projectID, err := parseUUID(input.ProjectID)
	if err != nil {
		return nil, err
	}
	note, err := q.CreateProjectNote(ctx, dbsqlc.CreateProjectNoteParams{UserID: userID, ProjectID: projectID, Body: input.Body})
	if err != nil {
		return nil, err
	}
	return toProjectNote(note), nil
}

// UpdateProjectNote is the resolver for the updateProjectNote field.
func (r *mutationResolver) UpdateProjectNote(ctx context.Context, id string, input model.UpdateProjectNoteInput) (*model.ProjectNote, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	noteID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	note, err := q.UpdateProjectNote(ctx, dbsqlc.UpdateProjectNoteParams{ID: noteID, UserID: userID, Body: nullString(input.Body)})
	if err != nil {
		return nil, err
	}
	return toProjectNote(note), nil
}

// DeleteProjectNote is the resolver for the deleteProjectNote field.
func (r *mutationResolver) DeleteProjectNote(ctx context.Context, id string) (bool, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return false, err
	}
	noteID, err := parseUUID(id)
	if err != nil {
		return false, err
	}
	return true, q.DeleteProjectNote(ctx, dbsqlc.DeleteProjectNoteParams{ID: noteID, UserID: userID})
}

// AddTodoDependency is the resolver for the addTodoDependency field.
func (r *mutationResolver) AddTodoDependency(ctx context.Context, todoID string, dependsOnTodoID string) (*model.Todo, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	tID, err := parseUUID(todoID)
	if err != nil {
		return nil, err
	}
	depID, err := parseUUID(dependsOnTodoID)
	if err != nil {
		return nil, err
	}
	if err := q.AddTodoDependency(ctx, dbsqlc.AddTodoDependencyParams{TodoID: tID, DependsOnTodoID: depID, UserID: userID}); err != nil {
		return nil, err
	}
	count, err := q.CountIncompleteDependencies(ctx, dbsqlc.CountIncompleteDependenciesParams{TodoID: tID, UserID: userID})
	if err != nil {
		return nil, err
	}
	if count > 0 {
		status := model.TodoStatusBlocked
		return r.UpdateTodo(ctx, todoID, model.UpdateTodoInput{Status: &status})
	}
	return r.getTodoModel(ctx, q, userID, tID)
}

// RemoveTodoDependency is the resolver for the removeTodoDependency field.
func (r *mutationResolver) RemoveTodoDependency(ctx context.Context, todoID string, dependsOnTodoID string) (*model.Todo, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	tID, err := parseUUID(todoID)
	if err != nil {
		return nil, err
	}
	depID, err := parseUUID(dependsOnTodoID)
	if err != nil {
		return nil, err
	}
	if err := q.RemoveTodoDependency(ctx, dbsqlc.RemoveTodoDependencyParams{TodoID: tID, DependsOnTodoID: depID, UserID: userID}); err != nil {
		return nil, err
	}
	return r.getTodoModel(ctx, q, userID, tID)
}

// GenerateAIProposal is the resolver for the generateAIProposal field.
func (r *mutationResolver) GenerateAIProposal(ctx context.Context, input model.GenerateAIProposalInput) (*model.AIProposal, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	parentID, err := parseUUID(input.ParentID)
	if err != nil {
		return nil, err
	}
	snapshot, err := r.aiContext(ctx, q, userID, input.ParentType.String(), parentID)
	if err != nil {
		return nil, err
	}
	plan, err := r.ai.GeneratePlan(ctx, input.MagicText, snapshot)
	if err != nil {
		return nil, err
	}
	proposalJSON, err := json.Marshal(plan)
	if err != nil {
		return nil, err
	}
	proposal, err := q.CreateAIProposal(ctx, dbsqlc.CreateAIProposalParams{
		UserID:       userID,
		ParentType:   input.ParentType.String(),
		ParentID:     parentID,
		MagicText:    input.MagicText,
		Summary:      plan.Summary,
		ProposalJson: proposalJSON,
	})
	if err != nil {
		return nil, err
	}
	return toAIProposal(proposal), nil
}

// AcceptAIProposal is the resolver for the acceptAIProposal field.
func (r *mutationResolver) AcceptAIProposal(ctx context.Context, id string) (*model.AIProposal, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	proposalID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	started := time.Now()
	slog.Info("ai proposal accept started", "proposalID", proposalID, "userID", userID)
	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		slog.Error("ai proposal accept transaction begin failed", "proposalID", proposalID, "err", err)
		return nil, err
	}
	defer tx.Rollback()

	tq := q.WithTx(tx)
	proposal, err := tq.GetAIProposal(ctx, dbsqlc.GetAIProposalParams{ID: proposalID, UserID: userID})
	if err != nil {
		slog.Error("ai proposal load failed", "proposalID", proposalID, "userID", userID, "err", err)
		return nil, err
	}
	if proposal.Status != model.AIProposalStatusDraft.String() {
		slog.Error("ai proposal accept rejected", "proposalID", proposalID, "status", proposal.Status, "err", "not draft")
		return nil, errors.New("ai proposal is not draft")
	}
	slog.Debug("ai proposal stored content",
		"proposalID", proposalID,
		"parentType", proposal.ParentType,
		"parentID", proposal.ParentID,
		"magicText", truncateGraphLogValue(proposal.MagicText),
		"proposalJson", truncateGraphLogValue(string(proposal.ProposalJson)),
	)
	var plan ai.Plan
	if err := json.Unmarshal(proposal.ProposalJson, &plan); err != nil {
		slog.Error("ai proposal stored json decode failed", "proposalID", proposalID, "err", err)
		return nil, err
	}
	slog.Info("ai proposal apply started",
		"proposalID", proposalID,
		"parentType", proposal.ParentType,
		"parentID", proposal.ParentID,
		"projectChanges", len(plan.Projects),
		"stageChanges", len(plan.Stages),
		"todoChanges", len(plan.Todos),
	)
	if err := r.applyAIPlan(ctx, tq, userID, proposal, plan); err != nil {
		slog.Error("ai proposal apply failed", "proposalID", proposalID, "duration", time.Since(started).String(), "err", err)
		return nil, err
	}
	applied, err := tq.MarkAIProposalApplied(ctx, dbsqlc.MarkAIProposalAppliedParams{ID: proposalID, UserID: userID})
	if err != nil {
		slog.Error("ai proposal mark applied failed", "proposalID", proposalID, "err", err)
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		slog.Error("ai proposal accept commit failed", "proposalID", proposalID, "err", err)
		return nil, err
	}
	slog.Info("ai proposal accept completed", "proposalID", proposalID, "duration", time.Since(started).String())
	return toAIProposal(applied), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	q, err := r.requireAdminQueries(ctx)
	if err != nil {
		return nil, err
	}
	users, err := q.ListUsers(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.User, 0, len(users))
	for _, user := range users {
		result = append(result, toUser(user))
	}
	return result, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	q, err := r.requireAdminQueries(ctx)
	if err != nil {
		return nil, err
	}
	userID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	user, err := q.GetUserByID(ctx, userID)
	if err != nil {
		return nil, err
	}
	return toUser(user), nil
}

// Epics is the resolver for the epics field.
func (r *queryResolver) Epics(ctx context.Context) ([]*model.Epic, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	epics, err := q.ListEpics(ctx, userID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Epic, 0, len(epics))
	for _, epic := range epics {
		result = append(result, toEpic(epic))
	}
	return result, nil
}

// Epic is the resolver for the epic field.
func (r *queryResolver) Epic(ctx context.Context, id string) (*model.Epic, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	epicID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	epic, err := q.GetEpic(ctx, dbsqlc.GetEpicParams{ID: epicID, UserID: userID})
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return toEpic(epic), nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, epicID *string) ([]*model.Project, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	filter, err := nullUUID(epicID)
	if err != nil {
		return nil, err
	}
	projects, err := q.ListProjects(ctx, dbsqlc.ListProjectsParams{UserID: userID, EpicID: filter})
	if err != nil {
		return nil, err
	}
	result := make([]*model.Project, 0, len(projects))
	for _, project := range projects {
		result = append(result, toProject(project))
	}
	return result, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	projectID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	project, err := q.GetProject(ctx, dbsqlc.GetProjectParams{ID: projectID, UserID: userID})
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return toProject(project), nil
}

// Stages is the resolver for the stages field.
func (r *queryResolver) Stages(ctx context.Context, projectID *string) ([]*model.Stage, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	pID := uuid.NullUUID{}
	if projectID != nil {
		parsed, err := parseUUID(*projectID)
		if err != nil {
			return nil, err
		}
		pID = uuid.NullUUID{UUID: parsed, Valid: true}
	}
	stages, err := q.ListStages(ctx, dbsqlc.ListStagesParams{ProjectID: pID, UserID: userID})
	if err != nil {
		return nil, err
	}
	result := make([]*model.Stage, 0, len(stages))
	for _, stage := range stages {
		result = append(result, toStage(stage))
	}
	return result, nil
}

// Stage is the resolver for the stage field.
func (r *queryResolver) Stage(ctx context.Context, id string) (*model.Stage, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	stageID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	stage, err := q.GetStage(ctx, dbsqlc.GetStageParams{ID: stageID, UserID: userID})
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return toStage(stage), nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, filter *model.TodoFilter) ([]*model.Todo, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	params := dbsqlc.ListTodosParams{UserID: userID}
	if filter != nil {
		if params.ProjectID, err = nullUUID(filter.ProjectID); err != nil {
			return nil, err
		}
		if params.StageID, err = nullUUID(filter.StageID); err != nil {
			return nil, err
		}
		if params.LabelID, err = nullUUID(filter.LabelID); err != nil {
			return nil, err
		}
		params.Priority = nullTodoPriority(filter.Priority)
		params.Status = nullTodoStatus(filter.Status)
	}
	todos, err := q.ListTodos(ctx, params)
	if err != nil {
		return nil, err
	}
	return r.todosWithLabels(ctx, q, userID, todos)
}

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, id string) (*model.Todo, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	todoID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	todo, err := q.GetTodo(ctx, dbsqlc.GetTodoParams{ID: todoID, UserID: userID})
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return r.todoWithLabels(ctx, q, userID, todo)
}

// Inbox is the resolver for the inbox field.
func (r *queryResolver) Inbox(ctx context.Context) ([]*model.Todo, error) {
	return r.todoList(ctx, func(q *dbsqlc.Queries, userID uuid.UUID) ([]dbsqlc.Todo, error) {
		return q.ListInboxTodos(ctx, userID)
	})
}

// OpenTodos is the resolver for the openTodos field.
func (r *queryResolver) OpenTodos(ctx context.Context) ([]*model.Todo, error) {
	return r.todoList(ctx, func(q *dbsqlc.Queries, userID uuid.UUID) ([]dbsqlc.Todo, error) {
		return q.ListOpenTodos(ctx, userID)
	})
}

// OverdueTodos is the resolver for the overdueTodos field.
func (r *queryResolver) OverdueTodos(ctx context.Context) ([]*model.Todo, error) {
	return r.todoList(ctx, func(q *dbsqlc.Queries, userID uuid.UUID) ([]dbsqlc.Todo, error) {
		return q.ListOverdueTodos(ctx, userID)
	})
}

// NextActions is the resolver for the nextActions field.
func (r *queryResolver) NextActions(ctx context.Context) ([]*model.Todo, error) {
	return r.todoList(ctx, func(q *dbsqlc.Queries, userID uuid.UUID) ([]dbsqlc.Todo, error) {
		return q.ListNextActionTodos(ctx, userID)
	})
}

// DoneTodos is the resolver for the doneTodos field.
func (r *queryResolver) DoneTodos(ctx context.Context) ([]*model.Todo, error) {
	return r.todoList(ctx, func(q *dbsqlc.Queries, userID uuid.UUID) ([]dbsqlc.Todo, error) {
		return q.ListDoneTodos(ctx, userID)
	})
}

// Labels is the resolver for the labels field.
func (r *queryResolver) Labels(ctx context.Context) ([]*model.Label, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	labels, err := q.ListLabels(ctx, userID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Label, 0, len(labels))
	for _, label := range labels {
		result = append(result, toLabel(label))
	}
	return result, nil
}

// ProjectNotes is the resolver for the projectNotes field.
func (r *queryResolver) ProjectNotes(ctx context.Context, projectID string) ([]*model.ProjectNote, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	pID, err := parseUUID(projectID)
	if err != nil {
		return nil, err
	}
	notes, err := q.ListProjectNotes(ctx, dbsqlc.ListProjectNotesParams{ProjectID: pID, UserID: userID})
	if err != nil {
		return nil, err
	}
	result := make([]*model.ProjectNote, 0, len(notes))
	for _, note := range notes {
		result = append(result, toProjectNote(note))
	}
	return result, nil
}

// TodoDependencies is the resolver for the todoDependencies field.
func (r *queryResolver) TodoDependencies(ctx context.Context, todoID string) ([]*model.TodoDependency, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	tID, err := parseUUID(todoID)
	if err != nil {
		return nil, err
	}
	deps, err := q.ListTodoDependencies(ctx, dbsqlc.ListTodoDependenciesParams{TodoID: tID, UserID: userID})
	if err != nil {
		return nil, err
	}
	result := make([]*model.TodoDependency, 0, len(deps))
	for _, dep := range deps {
		result = append(result, toTodoDependency(dep))
	}
	return result, nil
}

// Dashboard is the resolver for the dashboard field.
func (r *queryResolver) Dashboard(ctx context.Context) (*model.Dashboard, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	counts, err := q.DashboardCounts(ctx, userID)
	if err != nil {
		return nil, err
	}
	return &model.Dashboard{
		OpenTodos:         int(counts.OpenTodos),
		OverdueTodos:      int(counts.OverdueTodos),
		NextActions:       int(counts.NextActions),
		ActiveProjects:    int(counts.ActiveProjects),
		UpcomingDeadlines: int(counts.UpcomingDeadlines),
	}, nil
}

// ProjectProgress is the resolver for the projectProgress field.
func (r *queryResolver) ProjectProgress(ctx context.Context, projectID string) (*model.Progress, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	pID, err := parseUUID(projectID)
	if err != nil {
		return nil, err
	}
	progress, err := q.ProjectProgress(ctx, dbsqlc.ProjectProgressParams{ProjectID: uuid.NullUUID{UUID: pID, Valid: true}, UserID: userID})
	if err != nil {
		return nil, err
	}
	return progressModel(progress.Total, progress.Done), nil
}

// StageProgress is the resolver for the stageProgress field.
func (r *queryResolver) StageProgress(ctx context.Context, stageID string) (*model.Progress, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	sID, err := parseUUID(stageID)
	if err != nil {
		return nil, err
	}
	progress, err := q.StageProgress(ctx, dbsqlc.StageProgressParams{StageID: uuid.NullUUID{UUID: sID, Valid: true}, UserID: userID})
	if err != nil {
		return nil, err
	}
	return progressModel(progress.Total, progress.Done), nil
}

// AiProposal is the resolver for the aiProposal field.
func (r *queryResolver) AiProposal(ctx context.Context, id string) (*model.AIProposal, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	proposalID, err := parseUUID(id)
	if err != nil {
		return nil, err
	}
	proposal, err := q.GetAIProposal(ctx, dbsqlc.GetAIProposalParams{ID: proposalID, UserID: userID})
	if errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return toAIProposal(proposal), nil
}

// AiProposals is the resolver for the aiProposals field.
func (r *queryResolver) AiProposals(ctx context.Context, filter *model.AIProposalFilter) ([]*model.AIProposal, error) {
	q, userID, err := r.requireUserQueries(ctx)
	if err != nil {
		return nil, err
	}
	params := dbsqlc.ListAIProposalsParams{UserID: userID}
	if filter != nil {
		if filter.ParentType != nil {
			params.ParentType = sql.NullString{String: filter.ParentType.String(), Valid: true}
		}
		if filter.ParentID != nil {
			parentID, err := parseUUID(*filter.ParentID)
			if err != nil {
				return nil, err
			}
			params.ParentID = uuid.NullUUID{UUID: parentID, Valid: true}
		}
	}
	proposals, err := q.ListAIProposals(ctx, params)
	if err != nil {
		return nil, err
	}
	result := make([]*model.AIProposal, 0, len(proposals))
	for _, proposal := range proposals {
		result = append(result, toAIProposal(proposal))
	}
	return result, nil
}

// AiStatusReport is the resolver for the aiStatusReport field.
func (r *queryResolver) AiStatusReport(ctx context.Context, projectID string) (*model.AIStatusReport, error) {
	if _, err := parseUUID(projectID); err != nil {
		return nil, err
	}
	return &model.AIStatusReport{
		Summary: "AI integration is not configured yet.",
		Ready:   false,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
