// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_proposals.sql

package dbsqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createAIProposal = `-- name: CreateAIProposal :one
INSERT INTO ai_proposals (user_id, parent_type, parent_id, magic_text, summary, proposal_json)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, parent_type, parent_id, magic_text, summary, proposal_json, status, created_at, applied_at
`

type CreateAIProposalParams struct {
	UserID       uuid.UUID       `json:"user_id"`
	ParentType   string          `json:"parent_type"`
	ParentID     uuid.UUID       `json:"parent_id"`
	MagicText    string          `json:"magic_text"`
	Summary      string          `json:"summary"`
	ProposalJson json.RawMessage `json:"proposal_json"`
}

func (q *Queries) CreateAIProposal(ctx context.Context, arg CreateAIProposalParams) (AiProposal, error) {
	row := q.db.QueryRowContext(ctx, createAIProposal,
		arg.UserID,
		arg.ParentType,
		arg.ParentID,
		arg.MagicText,
		arg.Summary,
		arg.ProposalJson,
	)
	var i AiProposal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentType,
		&i.ParentID,
		&i.MagicText,
		&i.Summary,
		&i.ProposalJson,
		&i.Status,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const getAIProposal = `-- name: GetAIProposal :one
SELECT id, user_id, parent_type, parent_id, magic_text, summary, proposal_json, status, created_at, applied_at
FROM ai_proposals
WHERE id = $1 AND user_id = $2
`

type GetAIProposalParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetAIProposal(ctx context.Context, arg GetAIProposalParams) (AiProposal, error) {
	row := q.db.QueryRowContext(ctx, getAIProposal, arg.ID, arg.UserID)
	var i AiProposal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentType,
		&i.ParentID,
		&i.MagicText,
		&i.Summary,
		&i.ProposalJson,
		&i.Status,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const listAIProposals = `-- name: ListAIProposals :many
SELECT id, user_id, parent_type, parent_id, magic_text, summary, proposal_json, status, created_at, applied_at
FROM ai_proposals
WHERE user_id = $1
  AND ($2::text IS NULL OR parent_type = $2::text)
  AND ($3::uuid IS NULL OR parent_id = $3::uuid)
ORDER BY created_at DESC
`

type ListAIProposalsParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	ParentType sql.NullString `json:"parent_type"`
	ParentID   uuid.NullUUID  `json:"parent_id"`
}

func (q *Queries) ListAIProposals(ctx context.Context, arg ListAIProposalsParams) ([]AiProposal, error) {
	rows, err := q.db.QueryContext(ctx, listAIProposals, arg.UserID, arg.ParentType, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiProposal
	for rows.Next() {
		var i AiProposal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentType,
			&i.ParentID,
			&i.MagicText,
			&i.Summary,
			&i.ProposalJson,
			&i.Status,
			&i.CreatedAt,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAIProposalApplied = `-- name: MarkAIProposalApplied :one
UPDATE ai_proposals
SET status = 'APPLIED',
    applied_at = now()
WHERE id = $1 AND user_id = $2 AND status = 'DRAFT'
RETURNING id, user_id, parent_type, parent_id, magic_text, summary, proposal_json, status, created_at, applied_at
`

type MarkAIProposalAppliedParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkAIProposalApplied(ctx context.Context, arg MarkAIProposalAppliedParams) (AiProposal, error) {
	row := q.db.QueryRowContext(ctx, markAIProposalApplied, arg.ID, arg.UserID)
	var i AiProposal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentType,
		&i.ParentID,
		&i.MagicText,
		&i.Summary,
		&i.ProposalJson,
		&i.Status,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}
