// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const dashboardCounts = `-- name: DashboardCounts :one
SELECT
    COUNT(*) FILTER (WHERE status IN ('OPEN', 'IN_PROGRESS', 'BLOCKED'))::int AS open_todos,
    COUNT(*) FILTER (WHERE due_date < CURRENT_DATE AND status IN ('OPEN', 'IN_PROGRESS', 'BLOCKED'))::int AS overdue_todos,
    COUNT(*) FILTER (WHERE next_action = TRUE)::int AS next_actions,
    (SELECT COUNT(*)::int FROM projects WHERE status = 'ACTIVE' AND projects.user_id = $1) AS active_projects,
    COUNT(*) FILTER (WHERE due_date >= CURRENT_DATE AND due_date <= CURRENT_DATE + INTERVAL '7 days' AND status IN ('OPEN', 'IN_PROGRESS', 'BLOCKED'))::int AS upcoming_deadlines
FROM todos
WHERE user_id = $1
`

type DashboardCountsRow struct {
	OpenTodos         int32 `json:"open_todos"`
	OverdueTodos      int32 `json:"overdue_todos"`
	NextActions       int32 `json:"next_actions"`
	ActiveProjects    int32 `json:"active_projects"`
	UpcomingDeadlines int32 `json:"upcoming_deadlines"`
}

func (q *Queries) DashboardCounts(ctx context.Context, userID uuid.UUID) (DashboardCountsRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardCounts, userID)
	var i DashboardCountsRow
	err := row.Scan(
		&i.OpenTodos,
		&i.OverdueTodos,
		&i.NextActions,
		&i.ActiveProjects,
		&i.UpcomingDeadlines,
	)
	return i, err
}
