// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dependencies.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const addTodoDependency = `-- name: AddTodoDependency :exec
INSERT INTO todo_dependencies (todo_id, depends_on_todo_id)
SELECT $1, $2
WHERE EXISTS (SELECT 1 FROM todos WHERE todos.id = $1 AND todos.user_id = $3)
  AND EXISTS (SELECT 1 FROM todos WHERE todos.id = $2 AND todos.user_id = $3)
ON CONFLICT DO NOTHING
`

type AddTodoDependencyParams struct {
	TodoID          uuid.UUID `json:"todo_id"`
	DependsOnTodoID uuid.UUID `json:"depends_on_todo_id"`
	UserID          uuid.UUID `json:"user_id"`
}

func (q *Queries) AddTodoDependency(ctx context.Context, arg AddTodoDependencyParams) error {
	_, err := q.db.ExecContext(ctx, addTodoDependency, arg.TodoID, arg.DependsOnTodoID, arg.UserID)
	return err
}

const countIncompleteDependencies = `-- name: CountIncompleteDependencies :one
SELECT COUNT(*)::int
FROM todo_dependencies d
JOIN todos dep ON dep.id = d.depends_on_todo_id
JOIN todos t ON t.id = d.todo_id
WHERE d.todo_id = $1 AND t.user_id = $2 AND dep.status <> 'DONE'
`

type CountIncompleteDependenciesParams struct {
	TodoID uuid.UUID `json:"todo_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CountIncompleteDependencies(ctx context.Context, arg CountIncompleteDependenciesParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countIncompleteDependencies, arg.TodoID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listTodoDependencies = `-- name: ListTodoDependencies :many
SELECT d.todo_id, d.depends_on_todo_id, d.created_at
FROM todo_dependencies d
JOIN todos t ON t.id = d.todo_id
WHERE d.todo_id = $1 AND t.user_id = $2
ORDER BY d.created_at
`

type ListTodoDependenciesParams struct {
	TodoID uuid.UUID `json:"todo_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ListTodoDependencies(ctx context.Context, arg ListTodoDependenciesParams) ([]TodoDependency, error) {
	rows, err := q.db.QueryContext(ctx, listTodoDependencies, arg.TodoID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoDependency
	for rows.Next() {
		var i TodoDependency
		if err := rows.Scan(&i.TodoID, &i.DependsOnTodoID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTodoDependency = `-- name: RemoveTodoDependency :exec
DELETE FROM todo_dependencies
WHERE todo_id = $1 AND depends_on_todo_id = $2
  AND EXISTS (SELECT 1 FROM todos WHERE id = $1 AND user_id = $3)
`

type RemoveTodoDependencyParams struct {
	TodoID          uuid.UUID `json:"todo_id"`
	DependsOnTodoID uuid.UUID `json:"depends_on_todo_id"`
	UserID          uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTodoDependency(ctx context.Context, arg RemoveTodoDependencyParams) error {
	_, err := q.db.ExecContext(ctx, removeTodoDependency, arg.TodoID, arg.DependsOnTodoID, arg.UserID)
	return err
}
