// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: epics.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEpic = `-- name: CreateEpic :one
INSERT INTO epics (user_id, name, description, color, position)
VALUES ($1, $2, $3, $4, COALESCE($5, 0))
RETURNING id, user_id, name, description, color, position, created_at, updated_at
`

type CreateEpicParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Color       sql.NullString `json:"color"`
	Position    interface{}    `json:"position"`
}

func (q *Queries) CreateEpic(ctx context.Context, arg CreateEpicParams) (Epic, error) {
	row := q.db.QueryRowContext(ctx, createEpic,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Position,
	)
	var i Epic
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEpic = `-- name: DeleteEpic :exec
DELETE FROM epics
WHERE id = $1 AND user_id = $2
`

type DeleteEpicParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteEpic(ctx context.Context, arg DeleteEpicParams) error {
	_, err := q.db.ExecContext(ctx, deleteEpic, arg.ID, arg.UserID)
	return err
}

const getEpic = `-- name: GetEpic :one
SELECT id, user_id, name, description, color, position, created_at, updated_at
FROM epics
WHERE id = $1 AND user_id = $2
`

type GetEpicParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetEpic(ctx context.Context, arg GetEpicParams) (Epic, error) {
	row := q.db.QueryRowContext(ctx, getEpic, arg.ID, arg.UserID)
	var i Epic
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEpics = `-- name: ListEpics :many
SELECT id, user_id, name, description, color, position, created_at, updated_at
FROM epics
WHERE user_id = $1
ORDER BY position, created_at
`

func (q *Queries) ListEpics(ctx context.Context, userID uuid.UUID) ([]Epic, error) {
	rows, err := q.db.QueryContext(ctx, listEpics, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Epic
	for rows.Next() {
		var i Epic
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEpic = `-- name: UpdateEpic :one
UPDATE epics
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    color = COALESCE($3, color),
    position = COALESCE($4, position),
    updated_at = now()
WHERE id = $5 AND user_id = $6
RETURNING id, user_id, name, description, color, position, created_at, updated_at
`

type UpdateEpicParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Color       sql.NullString `json:"color"`
	Position    sql.NullInt32  `json:"position"`
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateEpic(ctx context.Context, arg UpdateEpicParams) (Epic, error) {
	row := q.db.QueryRowContext(ctx, updateEpic,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Position,
		arg.ID,
		arg.UserID,
	)
	var i Epic
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
