// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labels.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addTodoLabel = `-- name: AddTodoLabel :exec
INSERT INTO todo_labels (todo_id, label_id)
SELECT $1, $2
WHERE EXISTS (SELECT 1 FROM todos WHERE todos.id = $1 AND todos.user_id = $3)
  AND EXISTS (SELECT 1 FROM labels WHERE labels.id = $2 AND labels.user_id = $3)
ON CONFLICT DO NOTHING
`

type AddTodoLabelParams struct {
	TodoID  uuid.UUID `json:"todo_id"`
	LabelID uuid.UUID `json:"label_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) AddTodoLabel(ctx context.Context, arg AddTodoLabelParams) error {
	_, err := q.db.ExecContext(ctx, addTodoLabel, arg.TodoID, arg.LabelID, arg.UserID)
	return err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (user_id, name, color)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, color, created_at, updated_at
`

type CreateLabelParams struct {
	UserID uuid.UUID      `json:"user_id"`
	Name   string         `json:"name"`
	Color  sql.NullString `json:"color"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, createLabel, arg.UserID, arg.Name, arg.Color)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM labels
WHERE id = $1 AND user_id = $2
`

type DeleteLabelParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteLabel(ctx context.Context, arg DeleteLabelParams) error {
	_, err := q.db.ExecContext(ctx, deleteLabel, arg.ID, arg.UserID)
	return err
}

const listLabels = `-- name: ListLabels :many
SELECT id, user_id, name, color, created_at, updated_at
FROM labels
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListLabels(ctx context.Context, userID uuid.UUID) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoLabels = `-- name: ListTodoLabels :many
SELECT l.id, l.user_id, l.name, l.color, l.created_at, l.updated_at
FROM labels l
JOIN todo_labels tl ON tl.label_id = l.id
WHERE tl.todo_id = $1 AND l.user_id = $2
ORDER BY l.name
`

type ListTodoLabelsParams struct {
	TodoID uuid.UUID `json:"todo_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ListTodoLabels(ctx context.Context, arg ListTodoLabelsParams) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listTodoLabels, arg.TodoID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTodoLabel = `-- name: RemoveTodoLabel :exec
DELETE FROM todo_labels
WHERE todo_id = $1 AND label_id = $2
  AND EXISTS (SELECT 1 FROM todos WHERE id = $1 AND user_id = $3)
`

type RemoveTodoLabelParams struct {
	TodoID  uuid.UUID `json:"todo_id"`
	LabelID uuid.UUID `json:"label_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTodoLabel(ctx context.Context, arg RemoveTodoLabelParams) error {
	_, err := q.db.ExecContext(ctx, removeTodoLabel, arg.TodoID, arg.LabelID, arg.UserID)
	return err
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE labels
SET
    name = COALESCE($1, name),
    color = COALESCE($2, color),
    updated_at = now()
WHERE id = $3 AND user_id = $4
RETURNING id, user_id, name, color, created_at, updated_at
`

type UpdateLabelParams struct {
	Name   sql.NullString `json:"name"`
	Color  sql.NullString `json:"color"`
	ID     uuid.UUID      `json:"id"`
	UserID uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, updateLabel,
		arg.Name,
		arg.Color,
		arg.ID,
		arg.UserID,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
