// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProjectNote = `-- name: CreateProjectNote :one
INSERT INTO project_notes (user_id, project_id, body)
VALUES ($1, $2, $3)
RETURNING id, user_id, project_id, body, created_at, updated_at
`

type CreateProjectNoteParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Body      string    `json:"body"`
}

func (q *Queries) CreateProjectNote(ctx context.Context, arg CreateProjectNoteParams) (ProjectNote, error) {
	row := q.db.QueryRowContext(ctx, createProjectNote, arg.UserID, arg.ProjectID, arg.Body)
	var i ProjectNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectNote = `-- name: DeleteProjectNote :exec
DELETE FROM project_notes
WHERE id = $1 AND user_id = $2
`

type DeleteProjectNoteParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProjectNote(ctx context.Context, arg DeleteProjectNoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectNote, arg.ID, arg.UserID)
	return err
}

const listProjectNotes = `-- name: ListProjectNotes :many
SELECT id, user_id, project_id, body, created_at, updated_at
FROM project_notes
WHERE project_id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type ListProjectNotesParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ListProjectNotes(ctx context.Context, arg ListProjectNotesParams) ([]ProjectNote, error) {
	rows, err := q.db.QueryContext(ctx, listProjectNotes, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectNote
	for rows.Next() {
		var i ProjectNote
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectNote = `-- name: UpdateProjectNote :one
UPDATE project_notes
SET body = COALESCE($1, body),
    updated_at = now()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, project_id, body, created_at, updated_at
`

type UpdateProjectNoteParams struct {
	Body   sql.NullString `json:"body"`
	ID     uuid.UUID      `json:"id"`
	UserID uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateProjectNote(ctx context.Context, arg UpdateProjectNoteParams) (ProjectNote, error) {
	row := q.db.QueryRowContext(ctx, updateProjectNote, arg.Body, arg.ID, arg.UserID)
	var i ProjectNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
