// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, epic_id, name, description, status, start_date, target_date, position)
VALUES ($1, $2, $3, $4, COALESCE($5, 'ACTIVE'), $6, $7, COALESCE($8, 0))
RETURNING id, user_id, epic_id, name, description, status, start_date, target_date, position, created_at, updated_at
`

type CreateProjectParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	EpicID      uuid.NullUUID  `json:"epic_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      interface{}    `json:"status"`
	StartDate   sql.NullTime   `json:"start_date"`
	TargetDate  sql.NullTime   `json:"target_date"`
	Position    interface{}    `json:"position"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.UserID,
		arg.EpicID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.TargetDate,
		arg.Position,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpicID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.TargetDate,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1 AND user_id = $2
`

type DeleteProjectParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteProject, arg.ID, arg.UserID)
	return err
}

const detachStagesFromProject = `-- name: DetachStagesFromProject :exec
UPDATE stages
SET project_id = NULL, updated_at = now()
WHERE project_id = $1 AND user_id = $2
`

type DetachStagesFromProjectParams struct {
	ProjectID uuid.NullUUID `json:"project_id"`
	UserID    uuid.UUID     `json:"user_id"`
}

func (q *Queries) DetachStagesFromProject(ctx context.Context, arg DetachStagesFromProjectParams) error {
	_, err := q.db.ExecContext(ctx, detachStagesFromProject, arg.ProjectID, arg.UserID)
	return err
}

const detachTodosFromProject = `-- name: DetachTodosFromProject :exec
UPDATE todos
SET project_id = NULL, updated_at = now()
WHERE project_id = $1 AND user_id = $2
`

type DetachTodosFromProjectParams struct {
	ProjectID uuid.NullUUID `json:"project_id"`
	UserID    uuid.UUID     `json:"user_id"`
}

func (q *Queries) DetachTodosFromProject(ctx context.Context, arg DetachTodosFromProjectParams) error {
	_, err := q.db.ExecContext(ctx, detachTodosFromProject, arg.ProjectID, arg.UserID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, epic_id, name, description, status, start_date, target_date, position, created_at, updated_at
FROM projects
WHERE id = $1 AND user_id = $2
`

type GetProjectParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpicID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.TargetDate,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, user_id, epic_id, name, description, status, start_date, target_date, position, created_at, updated_at
FROM projects
WHERE user_id = $1
  AND ($2::uuid IS NULL OR epic_id = $2::uuid)
ORDER BY position, created_at
`

type ListProjectsParams struct {
	UserID uuid.UUID     `json:"user_id"`
	EpicID uuid.NullUUID `json:"epic_id"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, arg.UserID, arg.EpicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EpicID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.TargetDate,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectProgress = `-- name: ProjectProgress :one
SELECT
    COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE status = 'DONE')::int AS done
FROM todos
WHERE project_id = $1 AND user_id = $2
`

type ProjectProgressParams struct {
	ProjectID uuid.NullUUID `json:"project_id"`
	UserID    uuid.UUID     `json:"user_id"`
}

type ProjectProgressRow struct {
	Total int32 `json:"total"`
	Done  int32 `json:"done"`
}

func (q *Queries) ProjectProgress(ctx context.Context, arg ProjectProgressParams) (ProjectProgressRow, error) {
	row := q.db.QueryRowContext(ctx, projectProgress, arg.ProjectID, arg.UserID)
	var i ProjectProgressRow
	err := row.Scan(&i.Total, &i.Done)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    epic_id = COALESCE($1, epic_id),
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    status = COALESCE($4, status),
    start_date = COALESCE($5, start_date),
    target_date = COALESCE($6, target_date),
    position = COALESCE($7, position),
    updated_at = now()
WHERE id = $8 AND user_id = $9
RETURNING id, user_id, epic_id, name, description, status, start_date, target_date, position, created_at, updated_at
`

type UpdateProjectParams struct {
	EpicID      uuid.NullUUID  `json:"epic_id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Status      sql.NullString `json:"status"`
	StartDate   sql.NullTime   `json:"start_date"`
	TargetDate  sql.NullTime   `json:"target_date"`
	Position    sql.NullInt32  `json:"position"`
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.EpicID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.TargetDate,
		arg.Position,
		arg.ID,
		arg.UserID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EpicID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.TargetDate,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
