// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stages.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createStage = `-- name: CreateStage :one
INSERT INTO stages (user_id, project_id, name, description, status, start_date, target_date, position)
VALUES ($1, $2, $3, $4, COALESCE($5, 'PLANNED'), $6, $7, COALESCE($8, 0))
RETURNING id, user_id, project_id, name, description, status, start_date, target_date, position, created_at, updated_at
`

type CreateStageParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	ProjectID   uuid.UUID      `json:"project_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      interface{}    `json:"status"`
	StartDate   sql.NullTime   `json:"start_date"`
	TargetDate  sql.NullTime   `json:"target_date"`
	Position    interface{}    `json:"position"`
}

func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) (Stage, error) {
	row := q.db.QueryRowContext(ctx, createStage,
		arg.UserID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.TargetDate,
		arg.Position,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.TargetDate,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStage = `-- name: DeleteStage :exec
DELETE FROM stages
WHERE id = $1 AND user_id = $2
`

type DeleteStageParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteStage(ctx context.Context, arg DeleteStageParams) error {
	_, err := q.db.ExecContext(ctx, deleteStage, arg.ID, arg.UserID)
	return err
}

const getStage = `-- name: GetStage :one
SELECT id, user_id, project_id, name, description, status, start_date, target_date, position, created_at, updated_at
FROM stages
WHERE id = $1 AND user_id = $2
`

type GetStageParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetStage(ctx context.Context, arg GetStageParams) (Stage, error) {
	row := q.db.QueryRowContext(ctx, getStage, arg.ID, arg.UserID)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.TargetDate,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStages = `-- name: ListStages :many
SELECT id, user_id, project_id, name, description, status, start_date, target_date, position, created_at, updated_at
FROM stages
WHERE project_id = $1 AND user_id = $2
ORDER BY position, created_at
`

type ListStagesParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ListStages(ctx context.Context, arg ListStagesParams) ([]Stage, error) {
	rows, err := q.db.QueryContext(ctx, listStages, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stage
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.TargetDate,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stageProgress = `-- name: StageProgress :one
SELECT
    COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE status = 'DONE')::int AS done
FROM todos
WHERE stage_id = $1 AND user_id = $2
`

type StageProgressParams struct {
	StageID uuid.NullUUID `json:"stage_id"`
	UserID  uuid.UUID     `json:"user_id"`
}

type StageProgressRow struct {
	Total int32 `json:"total"`
	Done  int32 `json:"done"`
}

func (q *Queries) StageProgress(ctx context.Context, arg StageProgressParams) (StageProgressRow, error) {
	row := q.db.QueryRowContext(ctx, stageProgress, arg.StageID, arg.UserID)
	var i StageProgressRow
	err := row.Scan(&i.Total, &i.Done)
	return i, err
}

const updateStage = `-- name: UpdateStage :one
UPDATE stages
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    status = COALESCE($3, status),
    start_date = COALESCE($4, start_date),
    target_date = COALESCE($5, target_date),
    position = COALESCE($6, position),
    updated_at = now()
WHERE id = $7 AND user_id = $8
RETURNING id, user_id, project_id, name, description, status, start_date, target_date, position, created_at, updated_at
`

type UpdateStageParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Status      sql.NullString `json:"status"`
	StartDate   sql.NullTime   `json:"start_date"`
	TargetDate  sql.NullTime   `json:"target_date"`
	Position    sql.NullInt32  `json:"position"`
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateStage(ctx context.Context, arg UpdateStageParams) (Stage, error) {
	row := q.db.QueryRowContext(ctx, updateStage,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.TargetDate,
		arg.Position,
		arg.ID,
		arg.UserID,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.TargetDate,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
