// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const clearProjectNextActions = `-- name: ClearProjectNextActions :exec
UPDATE todos
SET next_action = FALSE, updated_at = now()
WHERE user_id = $1 AND project_id = $2 AND id <> $3
`

type ClearProjectNextActionsParams struct {
	UserID    uuid.UUID     `json:"user_id"`
	ProjectID uuid.NullUUID `json:"project_id"`
	ID        uuid.UUID     `json:"id"`
}

func (q *Queries) ClearProjectNextActions(ctx context.Context, arg ClearProjectNextActionsParams) error {
	_, err := q.db.ExecContext(ctx, clearProjectNextActions, arg.UserID, arg.ProjectID, arg.ID)
	return err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (user_id, project_id, stage_id, title, description, priority, status, start_date, due_date, estimated_effort, position, next_action, milestone, recurrence)
VALUES ($1, $2, $3, $4, $5, COALESCE($6, 'NORMAL'), COALESCE($7, 'OPEN'), $8, $9, $10, COALESCE($11, 0), COALESCE($12, FALSE), COALESCE($13, FALSE), COALESCE($14, 'NONE'))
RETURNING id, user_id, project_id, stage_id, title, description, priority, status, start_date, due_date, estimated_effort, position, next_action, milestone, recurrence, completed_at, created_at, updated_at
`

type CreateTodoParams struct {
	UserID          uuid.UUID      `json:"user_id"`
	ProjectID       uuid.NullUUID  `json:"project_id"`
	StageID         uuid.NullUUID  `json:"stage_id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	Priority        interface{}    `json:"priority"`
	Status          interface{}    `json:"status"`
	StartDate       sql.NullTime   `json:"start_date"`
	DueDate         sql.NullTime   `json:"due_date"`
	EstimatedEffort sql.NullString `json:"estimated_effort"`
	Position        interface{}    `json:"position"`
	NextAction      interface{}    `json:"next_action"`
	Milestone       interface{}    `json:"milestone"`
	Recurrence      interface{}    `json:"recurrence"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.UserID,
		arg.ProjectID,
		arg.StageID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.StartDate,
		arg.DueDate,
		arg.EstimatedEffort,
		arg.Position,
		arg.NextAction,
		arg.Milestone,
		arg.Recurrence,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.StageID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.StartDate,
		&i.DueDate,
		&i.EstimatedEffort,
		&i.Position,
		&i.NextAction,
		&i.Milestone,
		&i.Recurrence,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = $1 AND user_id = $2
`

type DeleteTodoParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, arg.ID, arg.UserID)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, user_id, project_id, stage_id, title, description, priority, status, start_date, due_date, estimated_effort, position, next_action, milestone, recurrence, completed_at, created_at, updated_at
FROM todos
WHERE id = $1 AND user_id = $2
`

type GetTodoParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTodo(ctx context.Context, arg GetTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.StageID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.StartDate,
		&i.DueDate,
		&i.EstimatedEffort,
		&i.Position,
		&i.NextAction,
		&i.Milestone,
		&i.Recurrence,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDoneTodos = `-- name: ListDoneTodos :many
SELECT id, user_id, project_id, stage_id, title, description, priority, status, start_date, due_date, estimated_effort, position, next_action, milestone, recurrence, completed_at, created_at, updated_at
FROM todos
WHERE user_id = $1 AND status = 'DONE'
ORDER BY completed_at DESC NULLS LAST, updated_at DESC
`

func (q *Queries) ListDoneTodos(ctx context.Context, userID uuid.UUID) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listDoneTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.StageID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.StartDate,
			&i.DueDate,
			&i.EstimatedEffort,
			&i.Position,
			&i.NextAction,
			&i.Milestone,
			&i.Recurrence,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxTodos = `-- name: ListInboxTodos :many
SELECT id, user_id, project_id, stage_id, title, description, priority, status, start_date, due_date, estimated_effort, position, next_action, milestone, recurrence, completed_at, created_at, updated_at
FROM todos
WHERE user_id = $1 AND project_id IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListInboxTodos(ctx context.Context, userID uuid.UUID) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listInboxTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.StageID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.StartDate,
			&i.DueDate,
			&i.EstimatedEffort,
			&i.Position,
			&i.NextAction,
			&i.Milestone,
			&i.Recurrence,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNextActionTodos = `-- name: ListNextActionTodos :many
SELECT id, user_id, project_id, stage_id, title, description, priority, status, start_date, due_date, estimated_effort, position, next_action, milestone, recurrence, completed_at, created_at, updated_at
FROM todos
WHERE user_id = $1 AND next_action = TRUE
ORDER BY due_date NULLS LAST, position, created_at
`

func (q *Queries) ListNextActionTodos(ctx context.Context, userID uuid.UUID) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listNextActionTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.StageID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.StartDate,
			&i.DueDate,
			&i.EstimatedEffort,
			&i.Position,
			&i.NextAction,
			&i.Milestone,
			&i.Recurrence,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenTodos = `-- name: ListOpenTodos :many
SELECT id, user_id, project_id, stage_id, title, description, priority, status, start_date, due_date, estimated_effort, position, next_action, milestone, recurrence, completed_at, created_at, updated_at
FROM todos
WHERE user_id = $1 AND status IN ('OPEN', 'IN_PROGRESS', 'BLOCKED')
ORDER BY
    CASE priority
        WHEN 'CRITICAL' THEN 0
        WHEN 'HIGH' THEN 1
        WHEN 'NORMAL' THEN 2
        ELSE 3
    END,
    due_date NULLS LAST,
    position,
    created_at
`

func (q *Queries) ListOpenTodos(ctx context.Context, userID uuid.UUID) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listOpenTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.StageID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.StartDate,
			&i.DueDate,
			&i.EstimatedEffort,
			&i.Position,
			&i.NextAction,
			&i.Milestone,
			&i.Recurrence,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueTodos = `-- name: ListOverdueTodos :many
SELECT id, user_id, project_id, stage_id, title, description, priority, status, start_date, due_date, estimated_effort, position, next_action, milestone, recurrence, completed_at, created_at, updated_at
FROM todos
WHERE user_id = $1
  AND due_date < CURRENT_DATE
  AND status IN ('OPEN', 'IN_PROGRESS', 'BLOCKED')
ORDER BY due_date, position, created_at
`

func (q *Queries) ListOverdueTodos(ctx context.Context, userID uuid.UUID) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listOverdueTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.StageID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.StartDate,
			&i.DueDate,
			&i.EstimatedEffort,
			&i.Position,
			&i.NextAction,
			&i.Milestone,
			&i.Recurrence,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodos = `-- name: ListTodos :many
SELECT id, user_id, project_id, stage_id, title, description, priority, status, start_date, due_date, estimated_effort, position, next_action, milestone, recurrence, completed_at, created_at, updated_at
FROM todos
WHERE user_id = $1
  AND ($2::uuid IS NULL OR project_id = $2::uuid)
  AND ($3::uuid IS NULL OR stage_id = $3::uuid)
  AND ($4::uuid IS NULL OR EXISTS (
      SELECT 1 FROM todo_labels tl WHERE tl.todo_id = todos.id AND tl.label_id = $4::uuid
  ))
  AND ($5::text IS NULL OR priority = $5::text)
  AND ($6::text IS NULL OR status = $6::text)
ORDER BY position, created_at
`

type ListTodosParams struct {
	UserID    uuid.UUID      `json:"user_id"`
	ProjectID uuid.NullUUID  `json:"project_id"`
	StageID   uuid.NullUUID  `json:"stage_id"`
	LabelID   uuid.NullUUID  `json:"label_id"`
	Priority  sql.NullString `json:"priority"`
	Status    sql.NullString `json:"status"`
}

func (q *Queries) ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos,
		arg.UserID,
		arg.ProjectID,
		arg.StageID,
		arg.LabelID,
		arg.Priority,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.StageID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.StartDate,
			&i.DueDate,
			&i.EstimatedEffort,
			&i.Position,
			&i.NextAction,
			&i.Milestone,
			&i.Recurrence,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET
    project_id = COALESCE($1, project_id),
    stage_id = COALESCE($2, stage_id),
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    priority = COALESCE($5, priority),
    status = COALESCE($6, status),
    start_date = COALESCE($7, start_date),
    due_date = COALESCE($8, due_date),
    estimated_effort = COALESCE($9, estimated_effort),
    position = COALESCE($10, position),
    next_action = COALESCE($11, next_action),
    milestone = COALESCE($12, milestone),
    recurrence = COALESCE($13, recurrence),
    completed_at = CASE
        WHEN $6::text = 'DONE' AND completed_at IS NULL THEN now()
        WHEN $6::text IS NOT NULL AND $6::text <> 'DONE' THEN NULL
        ELSE completed_at
    END,
    updated_at = now()
WHERE id = $14 AND user_id = $15
RETURNING id, user_id, project_id, stage_id, title, description, priority, status, start_date, due_date, estimated_effort, position, next_action, milestone, recurrence, completed_at, created_at, updated_at
`

type UpdateTodoParams struct {
	ProjectID       uuid.NullUUID  `json:"project_id"`
	StageID         uuid.NullUUID  `json:"stage_id"`
	Title           sql.NullString `json:"title"`
	Description     sql.NullString `json:"description"`
	Priority        sql.NullString `json:"priority"`
	Status          sql.NullString `json:"status"`
	StartDate       sql.NullTime   `json:"start_date"`
	DueDate         sql.NullTime   `json:"due_date"`
	EstimatedEffort sql.NullString `json:"estimated_effort"`
	Position        sql.NullInt32  `json:"position"`
	NextAction      sql.NullBool   `json:"next_action"`
	Milestone       sql.NullBool   `json:"milestone"`
	Recurrence      sql.NullString `json:"recurrence"`
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo,
		arg.ProjectID,
		arg.StageID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.StartDate,
		arg.DueDate,
		arg.EstimatedEffort,
		arg.Position,
		arg.NextAction,
		arg.Milestone,
		arg.Recurrence,
		arg.ID,
		arg.UserID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.StageID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.StartDate,
		&i.DueDate,
		&i.EstimatedEffort,
		&i.Position,
		&i.NextAction,
		&i.Milestone,
		&i.Recurrence,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
