// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_subject, email, name, approved, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.Name,
		&i.Approved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (google_subject, email, name, approved)
VALUES ($1, $2, $3, $4)
ON CONFLICT (google_subject) DO UPDATE
SET email = EXCLUDED.email,
    name = EXCLUDED.name,
    approved = users.approved OR EXCLUDED.approved,
    updated_at = now()
RETURNING id, google_subject, email, name, approved, created_at, updated_at
`

type UpsertUserParams struct {
	GoogleSubject string `json:"google_subject"`
	Email         string `json:"email"`
	Name          string `json:"name"`
	Approved      bool   `json:"approved"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.GoogleSubject,
		arg.Email,
		arg.Name,
		arg.Approved,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.Name,
		&i.Approved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
