// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbsqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_subject, email, name, approved, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.Name,
		&i.Approved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, google_subject, email, name, approved, created_at, updated_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GoogleSubject,
			&i.Email,
			&i.Name,
			&i.Approved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    approved = COALESCE($1, approved),
    updated_at = now()
WHERE id = $2
RETURNING id, google_subject, email, name, approved, created_at, updated_at
`

type UpdateUserParams struct {
	Approved sql.NullBool `json:"approved"`
	ID       uuid.UUID    `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Approved, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.Name,
		&i.Approved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (google_subject, email, name, approved)
VALUES ($1, $2, $3, $4)
ON CONFLICT (google_subject) DO UPDATE
SET email = EXCLUDED.email,
    name = EXCLUDED.name,
    approved = users.approved OR EXCLUDED.approved,
    updated_at = now()
RETURNING id, google_subject, email, name, approved, created_at, updated_at
`

type UpsertUserParams struct {
	GoogleSubject string `json:"google_subject"`
	Email         string `json:"email"`
	Name          string `json:"name"`
	Approved      bool   `json:"approved"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.GoogleSubject,
		arg.Email,
		arg.Name,
		arg.Approved,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSubject,
		&i.Email,
		&i.Name,
		&i.Approved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
